zendesk/zendesk_apps_tools

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb
:koala:
Allow setting of the app id so we can use ZAT for testing existing installations of apps that use Secure Requests without having to re-upload them. ZAS uses the same id for the installation as well, so oddly you'll usually want to use the installation id and not the app id for the app id. :/
- None
=> Allow setting of the app id

lib/zendesk_apps_tools/translate.rb, spec/fixture/i18n_app_pseudotranslate/translations/en.json, spec/fixture/i18n_app_pseudotranslate/translations/expected.json, spec/lib/zendesk_apps_tools/translate_spec.rb
Build in a pseudotranslate function.  This function is similar to what Rosetta does for psuedotranslation.  It simply takes the English string and adds some unique markers to the beginning and end of the string. This allows devs to easily find them, and helps with spacing requirements. 
/cc @princemaple @pdeuter 
@princemaple can you tag others if necessary? 
- Jira link: https://zendesk.atlassian.net/browse/LOCAL-580
- Low. This just adds another command to the translate library.
=> build in a pseudotranslate function

Gemfile.lock, lib/zendesk_apps_tools/server.rb, zendesk_apps_tools.gemspec
Use the locale parameter sent by the classic apps helper. 
/cc @pdeuter @benhass @princemaple 
- Classic Change: https://github.com/zendesk/zendesk/pull/16964
- Low. Just adding a key into the parameters hash.
=> pass locale to ZAS Package

Gemfile.lock, zendesk_apps_tools.gemspec
:koala:
List of changes is [here](https://github.com/zendesk/zendesk_apps_support/compare/v1.17.2...v1.18.0)
0.5 apps will now be deprecated, i.e. we will still serve apps targeting the deprecated version, but newly created or updated apps CANNOT target it
- Forcing people to update their apps, making some developers angry
=> Bump ZAS to 1.18.0

doc/tools.md
**Description**
Not _deja vu_. The ZAT doc is in a different repo from the rest of the framework docs.
* Add a ZAT limitations with secure requests and requirements to the section about the ZAT server
* Refresh some old links with new S3 and HC links
**Reference**
* [Ticket 1131894](https://support.zendesk.com/agent/tickets/1131894)
@maximeprades @pmgrove @angiesaurus
=> Add note about server limitations

doc/tools.md
:koala:
I was walking through the app developer docs for the first time and working the examples.
When I hit this blurb on how to pass parameters to the app via the -c parameter I fell down a 45 min rabbit hole where I tried to figure out how to reference/use values passed as parameters/settings. 
Once I found the Settings page it was pretty clear - however adding a quick example here might help others to not stumble on this.
/cc @zendesk/quokka, @chucknado 
Visit the production page:
https://developer.zendesk.com/apps/docs/agent/tools
- None
=> Developer docs enhancement

lib/zendesk_apps_tools/server.rb
:koala:
This allows developers to include an iframe from the assets folder when using ZAT.
/cc @zendesk/quokka @fandoweb 
- None
=> Disable frame_options protection

app_template/translations/en.json, app_template_iframe/translations/en.json, features/new.feature
:bread: 
Make app template use the default i18n format as documented [here](https://developer.zendesk.com/apps/docs/agent/i18n).
* HC community: https://support.zendesk.com/hc/en-us/community/posts/209137097-Whats-the-purpose-of-the-package-app-that-messes-with-translations- 
* [low] Translations may not work for new apps created using ZAT
=> Make app template use the default i18n format as documented

lib/zendesk_apps_tools/package_helper.rb
Allow packing apps with .scss files.
See zendesk/zendesk_apps_support#109 for additional details on the need for .scss file packing.
=> Allow packing .scss file

lib/zendesk_apps_tools/deploy.rb
@zendesk/vegemite bring our handling of invalid json when polling the job status in line with the way we handle it everywhere else
=> replace an unhandled crash with a handled crash

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
/cc @zendesk/vegemite @zendesk/wombat 
Just tested this with a `zat update`, seemed to work fine.
Removes these warnings:
```
/Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/multipart-post-1.2.0/lib/composite_io.rb:19: warning: UploadIO#respond_to?(:to_ary) is old fashion which takes only one parameter
/Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/multipart-post-1.2.0/lib/composite_io.rb:105: warning: respond_to? is defined here
```
* [low] network calls do not behave as we expect
=> bump faraday and multipart-post

lib/zendesk_apps_tools/server.rb
:v:
Browsers turn out to be draconian when it comes to getting anything else than an images or a javascript file.
Turns out 2 headers were added which makes this a CORS request with a preflight where we need to allow those headers
This PR satisfies all that, so i can load a .txt or .json file from my assets folder.
* JIRA:
=> Satisfy preflight requests

Gemfile.lock, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb, zendesk_apps_tools.gemspec
@zendesk/vegemite currently if you have a file like `assets/client/build/index.html` it will 404. Something to do with the `File.join`.
`public_folder` can't be set inside `server.rb` because that is run before we set the `path`.
=> allow serving files from nested asset directories with CORS

lib/zendesk_apps_tools/command.rb
`jshintrb` is not compatible with JScript, the JS runtime that ships with windows.
Installing node standalone is easier than any of the other [supported runtimes](https://github.com/rails/execjs/blob/master/lib/execjs/runtimes.rb#L82-L90) due to their compilation toolchains.
=> explain the easiest solution for validation on windows

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/deploy.rb
modified this method to no longer need `self` passed in, it's saved in the constructor now.
=> fix crash in zat server

Gemfile.lock, zendesk_apps_tools.gemspec
Oops, my local version of ZAS was built against https://github.com/zendesk/zendesk_apps_support/pull/131 now the Gemfile.lock is broken:
https://travis-ci.org/zendesk/zendesk_apps_tools/jobs/156989834
ZAS 3.1.0 depends on json-stream, 3.1.1 does not.
=> fix dev environment

features/new.feature, features/package.feature, features/step_definitions/app_steps.rb, lib/zendesk_apps_tools/command.rb
Makes the default output of `zat new` to be a v2 app.
come on @pmgrove what's the story?
- [low] `zat new` doesn't work or surprises people
=> make v2 apps the default

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/command_helpers.rb, lib/zendesk_apps_tools/common.rb, lib/zendesk_apps_tools/translate.rb, spec/lib/zendesk_apps_tools/common_spec.rb, spec/lib/zendesk_apps_tools/settings_spec.rb, spec/lib/zendesk_apps_tools/translate_spec.rb
- Refactor the way we do shared_options because thor's `method_options` doesn't provide as much niceness as `method_option`.
- Implement a `--unattended` option for some commands so that nobody is ever left with a stuck prompt waiting for input.
- Refactor of `zat translate SUBCOMMAND` especially `zat translate update` to be more consistent with linter rules and to `exit 1` instead of `exit 0` on error
cc @zendesk/vegemite @zendesk/wombat 
https://zendesk.atlassian.net/browse/OFFAPPS-691
- [low] since this affects options across many commands, many of them might crash / not work
=> OFFAPPS-691 zat translate update --unattended

lib/zendesk_apps_tools/command.rb
Adding support to allow binding a specific ip address when using zat server. This would be useful for our case when developing using a vagrant/virtual machine, as we tend to bind our tools to 0.0.0.0 when testing and setup our virtual machine to allow access to the virtual machine through a specific ip/host.
=> Adding support for binding using zat server

lib/zendesk_apps_tools/settings.rb, spec/fixture/config/settings.yml, spec/lib/zendesk_apps_tools/settings_spec.rb
Fixes a bug where falsey values in `settings.yml` or `settings.json` get overridden by the default for that setting.
- https://zendesk-appdevelopers.slack.com/archives/apps-framework/p1478420251000091
- https://gist.github.com/joelhellman/b30c9edc094f3cc3f371c4c584a890c8
=> handle false values in settings files if there is also a default

Gemfile.lock, zendesk_apps_tools.gemspec
Bumps the zendesk apps support gem from 3.1.4 to 3.1.5 to support the new ticket_editor location.
**Risks**:
Might introduce functionality not yet properly supported in production (the new ticket_editor location).
**Mitigations**:
This should be okay to go, pending a green light on Jenkins.
=> bump zendesk apps support to 3.1.5

lib/zendesk_apps_tools/command.rb
https://support.zendesk.com/hc/en-us/community/posts/235344447
=> show a useful error when there is no JS runtime at all

.travis.yml, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/common.rb, lib/zendesk_apps_tools/server.rb, lib/zendesk_apps_tools/settings.rb
I think it's better to do this because foreman in the app scaffold will dump a bunch of webpack output after asking for a setting, this caused confusion.
=> support --unattended in zat server, read default parameters instead of crashing

bin/zat, lib/zendesk_apps_tools/command.rb
Fixes a crash:
```
/Users/rsandler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-1.35.11/bin/zat:3:in `shift': no implicit conversion of String into Integer (TypeError)
from /Users/rsandler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-1.35.11/bin/zat:3:in `<top (required)>'
from /Users/rsandler/.rbenv/versions/2.3.3/bin/zat:22:in `load'
from /Users/rsandler/.rbenv/versions/2.3.3/bin/zat:22:in `<main>'
```
and a warning:
```
Expected string default value for '--port'; got 4567 (numeric)
Expected string default value for '--app-id'; got 0 (numeric)
```
cc @zendesk/vegemite 
https://support.zendesk.com/agent/tickets/2051273
- [low] zat still not working on ruby 2.3.3
=> fix load path on ruby 2.3.3, fix warning

lib/zendesk_apps_tools/translate.rb, spec/lib/zendesk_apps_tools/translate_spec.rb
/cc @zendesk/undefined
When specifying an optional path flag, prevent the root directory name being recreated and nested i.e. stop stuff like `/dist/dist/translations/` happening
* JIRA: AF-564
=> Fix write directory for translations

app_template_iframe/assets/iframe.html
#:v:
Include zendesk garden in iframe template for all new v2 apps created with zat.
* [low] include base stylesheet in new apps, no more ugly default fonts
=> Include zendesk garden in iframe template

lib/zendesk_apps_tools/command.rb
Hey guys, if we have a line in an app like the [following](https://github.com/zendesk/timetracking_app/blob/master/app.js#L66):
```onAppCreated: function() {
if (this.installationId()) {
... blah blah here
}
```
if you are running the app from zat (which I think this conditional is checking for), the installationId() method was returning a string '0' by default, which is truthy. I've changed ZAT to only use a default app_id of the numeric 0 where necessary. I suppose I could just do `parseInt(this.installationId(), 10)` instead, but I wanted to see why this was happening at the source.
I took a look at Thor's [Method Options](https://github.com/erikhuda/thor/wiki/Method-Options) docs as a reference for forcing a numeric type.
Thoughts?
=> Make app_id default to a numeric value instead of a string

bin/zat
Point people in the right direction to avoid encoding dramas.
Hard to give more specific instructions though - they depend on the platform, shell and how long-lived they want the change to be.
We shouldn't set this variable on a user's behalf either, both because it may clobber an encoding they intentionally and it may overwrite other settings in `RUBYOPT`.
https://support.zendesk.com/hc/en-us/community/posts/203461336-Problems-with-accents-in-templates-
- [medium] zat stops working on certain windows versions if they don't support UTF-8.
=> warn and set to UTF-8 as early as possible

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb
:v:
You can set the app id, but not the install id. This PR allows you to set the install id. Useful for using the proxy and testing currently installed apps locally.
* JIRA: 
- [low] technically when using app_id it doesn't set install_id anymore.
=> Set install_id from ZAT

Gemfile.lock, zendesk_apps_tools.gemspec
@zendesk/sustaining 
rubyzip ( < 1.2.1 ) is vulnerable to directory traversals. A malicious user can prepend ../ to the file’s directory path to traverse the directory to create and overwrite arbitrary files.
Ref: https://support.zendesk.com/agent/tickets/2316100
=> Bump rubyzip

lib/zendesk_apps_tools/translate.rb
Currently when we do `zat translate update --unattended` we see output like this when nothing has changed:
```
force  translations/ar.json
force  translations/pt-br.json
identical  translations/en-gb.json
force  translations/bg.json
identical  translations/en-ca.json
force  translations/fr-ca.json
force  translations/cs.json
force  translations/da.json
identical  translations/nl.json
identical  translations/en-US.json
force  translations/es-es.json
force  translations/fi.json
force  translations/fr.json
force  translations/de.json
force  translations/it.json
force  translations/ja.json
force  translations/ko.json
force  translations/es-419.json
force  translations/no.json
force  translations/pl.json
force  translations/pt.json
force  translations/ro.json
force  translations/ru.json
force …
```
=> fix code that detects whether translation files have changed or not

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/deploy.rb, lib/zendesk_apps_tools/package_helper.rb, lib/zendesk_apps_tools/server.rb, spec/lib/zendesk_apps_tools/command_spec.rb
When you `zat create` you almost always go and install the app afterwards. This does it automatically.
cc @zendesk/vegemite @fvzzy 
Poll the job when the installation has requirements
- [low] `zat create` failing
=> install after zat create

.travis.yml, features/create.feature, features/step_definitions/app_steps.rb, features/support/helpers.rb, features/support/webmock.rb, lib/zendesk_apps_tools/command.rb
`zat create --no-install` crashes because it passes the `--no-install` argument on to `validate`.
cc @zendesk/vegemite 
https://zendesk-appdevelopers.slack.com/archives/C0L7VFW9G/p1490251653651834
=> just call validate rather than invoking

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb
Sinatra's static file serving seems to take precedence over our defined routes. This is bad in the case that we want to _generate_ `app.js` rather than just serve it from `assets/`.
Helpfully, we've already monkey patched its `send_file` method, so let's monkey patch some more.
cc @zendesk/vegemite @dashedstripes 
- [low] `zat server` is broken for some apps
=> at least try to serve the app even if assets/app.js exists

features/support/webmock.rb, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/command_spec.rb
#:bear:
/cc @zendesk/wombat
This is part of the multi product effort
`zat create` to install the app in all product locations found in manifest.
Depends on the ZAM PR listed below
* JIRA: https://zendesk.atlassian.net/browse/APPS-3473
* ZAM PR: https://github.com/zendesk/zendesk_app_market/pull/2599
* low - breaks app creation/installation
=> [APPS-3473] Multi Product - Use v3 app market endpoints and install in multiple products

lib/zendesk_apps_tools/package_helper.rb
Previously the error message when trying to run `zat s` in the wrong directory was unhelpful.
A guard has now been added that catches the previously uncaught error and displays a message guiding the user where to look.
- Check out `nickf/better-error-handling` branch
- `bundle i`
- If you haven't already, set up an alias in your shell profile (.bash_profile, .zshrc, whatever you use), and change the path in the command  
for example: `alias zatdev='BUNDLE_GEMFILE=/path/to/repo/zendesk_apps_tools/Gemfile bundle exec /path/to/repo/zendesk_apps_tools/bin/zat'`  
You might need to `source` your profile to refresh the changes (or open a new Terminal window)
- Go to a folder that does not contain a `manifest.json`
- `zatdev s`
- See the error message
- Go to a folder that …
=> Add guard for wrong path

features/create.feature, features/support/webmock.rb, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/common.rb, spec/lib/zendesk_apps_tools/command_spec.rb
Add version checking to ZAT.
When a check is made, the version number and the date it was last checked are both saved to the `.zat` file for caching and so it wouldn't happen every time the validate command was called. Currently it will only check if the last time a check was made was more than a week ago.
Checks are performed by querying the RubyGems API for the version.
The cached values are only saved to the project's local `.zat` file, as opposed to a global, root `.zat` file. Maybe that could be a future feature improvement.
- Check out `nickf/add-version-checks` branch
- `bundle i`
- If you haven't already, set up an alias in your shell profile (.bash_profile, .zshrc, whatever you use), and change the path in the command  
for example: `alias …
=> Add version checking

Gemfile.lock, zendesk_apps_tools.gemspec
Bumping ZAS version to support new chat background app location.
Chat FE PR: https://github.com/zopim/meshim-frontend/pull/3473
ZAS Changes: https://github.com/zendesk/zendesk_apps_support/pull/173
@zendesk/vegemite
=> Bump ZAS to v4.0.0

Gemfile.lock, zendesk_apps_tools.gemspec
Wombat have made some ZAS bumps recently. This PR makes ZAT use the latest version of ZAS.
[From v4.0.0 to v4.1.0](https://github.com/zendesk/zendesk_apps_support/compare/v4.0.0...v4.1.0):
- Updated some translation strings
[From v4.1.0 to v4.2.0](https://github.com/zendesk/zendesk_apps_support/compare/v4.1.0...v4.2.0):
- Only remove name in translation.json for non-default locale
- [low] Strings aren't removed from default locale JSON, but will be ignored from other places so not a big worry.
=> Bump ZAS to v4.2.0

Gemfile.lock, lib/zendesk_apps_tools/command.rb, zendesk_apps_tools.gemspec
Stops `zat validate` from completely falling over.
=> Add require statement for ExecJS

lib/zendesk_apps_tools/command.rb, spec/lib/zendesk_apps_tools/command_spec.rb
✌️ 
Adds support for a `zat migrate` command that will shell out to the [Zendesk App Migration Helper](https://github.com/zendesk/zendesk_app_migrator).
Before attempting to run the Migration Helper, zat will:
1. Check whether Node.js is installed (and by extension, NPM)
1. Check whether the App Migration Helper is installed
1. Run the App Migration Helper (with any options passed to zat)
- https://zendesk.atlassian.net/browse/AF-775
- N/A
=> [AF-775] Create ZAT migrate command

lib/zendesk_apps_tools/common.rb, lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/command_spec.rb, spec/lib/zendesk_apps_tools/common_spec.rb
✌️
**Overview**
Currently `zat update` fails silently when `app_id` cannot be found. Here's what is happening:
- We query `apps.json` endpoint and pass the response to `JSON.parse`. The response might be empty string due to many reasons: wrong credentials, no internet connection, etc
- When `JSON.parse(value)` fails, we use `value` itself as error message. However, `value` is empty string so it simply goes silent.
**Todo**
**References**
https://zendesk.atlassian.net/browse/AF-858
**Risks**
N/A
=> Fix silent zat update failure when app_id is not found

lib/zendesk_apps_tools/server.rb
After switching to thin from webbrick, the logging for the server has stoped. Currently logging for the sever in v2.4.0 results in the following:
```
▶ bundle exec ruby bin/zat s --path=../foobar_foobar
Enter a value for optional parameter 'token' or press 'Return' to skip:
== Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
^CStopping ...
Stopping ...
== Sinatra has ended his set (crowd applauds)
```
This PR would re-enable logging for the server. Which would result in the following:
```
▶ bundle exec ruby bin/zat s --path=../foobar_foobar
Enter a value for optional parameter 'token' or press 'Return' to skip:
== Sinatra (v1.4.8) has …
```
=> Re-enable logging for server

lib/zendesk_apps_tools/package_helper.rb
had an error in my json and zat kept telling me that the file does not exist ... not very helpful ...
with this change it now shows the full backtrace, which is much more helpful
```
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse': 743: unexpected token at '{ (JSON::ParserError)
"name": "Agent Satisfaction App",
"author": {
```
... but still fails nicely when the file is indeed missing
@chucknado @zendesk/vegemite
=> do not hide errors like json parse errors

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Bump ZAS to replace SVGs containing embedded bitmaps with a placeholder SVG.
* JIRA: https://zendesk.atlassian.net/browse/AF-952
* ZAS PR: https://github.com/zendesk/zendesk_apps_support/pull/194
* None/Low - new sanitisation rules cause validation to fail.
=> [AF-952] Bump ZAS to v4.6.4

lib/zendesk_apps_tools/command.rb
✌️
When running ZAT commands under certain Ruby versions, the `FileUtils` class wasn't being auto-loaded, resulting in a `NameError`.
```
c:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.3/lib/zendesk_apps_tools/command.rb:128:in `clean': uninitialized constant ZendeskAppsTools::Command::FileUtils (NameError)
Did you mean?  FileTest
from c:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
...
```
- Ticket: https://support.zendesk.com/agent/tickets/3408278
- [low] The explicit require should work in all scenarios, making an auto-load unnecessary
=> [ZD3408278][AF-1046] 'zat' errors out on 'clean' with "uninitialized" FileUtils

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/command_spec.rb
When the app ID provided in `.zat` is invalid and `zat update` is performed, the user gets a `RecordNotFound` (or `Internal Server Error` as reported in the Z1 ticket) error, which is unhelpful.
This PR adds a check to see if the app is installed, and bails early if otherwise.
@zendesk/sustaining @zendesk/vegemite 
* https://support.zendesk.com/agent/tickets/3725488
* Low: Might break private app updates via `zat update`
=> ZD3725488 Exit early when app ID is invalid

lib/zendesk_apps_tools/command.rb
When we execute `zat create` the app is installed multiple times(number of location times) per product.
This is caused due to a minor error in logic here: 
```
manifest.location_options.collect{ |option| option.location.product_code }
```
Consider an example where the manifest looks something like this:
```
"location": {
"support": {
"ticket_sidebar":"http://localhost:44000/parent",
"modal": "http://localhost:44000/modal"
}
},
```
Now based on the above logic, we are transforming an array of 2 element like this:
`
[
{'location':'ticket_sidebar', 'product_code': 1, .... },
{'location':'modal', 'product_code': 1, .... }
]
` ==> `[1,1]`
The fix is just to return uniq values.
[LOW] There is only one consumer for the `product_codes` function that is modified in this PR, that …
=> [AF-1067] Only return uniq product_codes

lib/zendesk_apps_tools/translate.rb, spec/lib/zendesk_apps_tools/translate_spec.rb
Switch local endpoint as suggested by the i18n team from `https://support.zendesk.com/api/v2/locales/agent.json` to `https://support.zendesk.com/api/v2/locales/apps/admin.json`.
@zendesk/vegemite @zendesk/i18n
=> [AF-1127] Switch locale endpoint

lib/zendesk_apps_tools/command.rb
:v:
@zendesk/apps-migration 
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-1038
* [medium] `zat new --scaffold` shouldn't affect existing command options `zat new`, `zat new --v1`, `zat new --iframe-only`
* [low] `zat migrate` should work as normal, it directly invoke the app_migrator executable, doesn't aware of the internal change of it.
=> [OFFAPPS-1038] Update ZAT to support `zat new --scaffold` command option

Gemfile.lock, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/version.rb, spec/lib/zendesk_apps_tools/command_spec.rb
:v:
@zendesk/apps-migration 
* [low] `zat new --scaffold` should not break
=> Replace 2.4 method match? with 2.0 compatible method match

lib/zendesk_apps_tools/theme.rb
It might happen that the local theme is in a directory called e.g.: `cph_with_alternate_templates`. In such case, the former regex would have captured `templates/footer` instead of just `footer`. The proposed regex takes a greedy approach and matches the path after the last occurrence of `templates/`.
@zendesk/guide-growth
=> Improve the regular expression used to extract the template identifier from the path

README.md
While trying to configure how to get ZAT's web server to listen on `0.0.0.0` for testing with external devices / VMs, I found out that the instructions were not conclusive to a working state.
I found what I think is a fix, at least it lets me run a successful `bundle install` in ZAT repo while pointing at local `ZAS`.
=> Update local dev instructions with gemspec usage

lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/cache_spec.rb, spec/lib/zendesk_apps_tools/command_spec.rb, spec/lib/zendesk_apps_tools/deploy_spec.rb
:v:
While working on a sprint task, I came across some ruby code that doesn't look great. Thought I'd clean it up abit before working on that sprint task. This change follows the [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide).
Prior to the refactoring, I created a test for the code that is to be refactored. Then made sure that the test passes after refactoring
1. Write Test for method
2. Refactor method
3. Run test for new method
4. Explicitly declare external dependencies (modules)
1. Better way to write `.empty?` condition
```
response_json = ""
app_json =  response_json.empty? ? nil : 'method_name' <--(!!!)
app_json = 'method_name' unless response_json.empty? <---(Better way)
(because app_json will be nil otherwise anyway)
```
2. get_connection …
=> Refactor find_app_id in ZendeskAppsTools::Deploy

lib/zendesk_apps_tools/api_connection.rb, spec/lib/zendesk_apps_tools/api_connection_spec.rb, spec/lib/zendesk_apps_tools/cache_spec.rb, spec/lib/zendesk_apps_tools/command_spec.rb
cc: @zendesk/vegemite 
Previously when a developer tries to `zat create` or `zat update`, the CLI prompts developers to input account subdomain and email (as username). 
There was no validation around these input, resulting in ZAT trying to access invalid urls such as
`myzendesksubdomain.zendesk.com.zendesk.com`
1. Put Validation around subdomains, full urls and email (username) using regex. Use ruby method `!!foo.match(bar)` to determine if they match. `.match?` is only available for newer versions of Ruby.
2. Regular Expression for Email is **explicitly** defined instead of using `URI::MailTo::EMAIL_REGEXP || URI::MailTo::MAILTO_REGEXP` as `URI::MailTo::MAILTO_REGEXP` is not entirely accurate.
3. Regular Expression for full url and subdomain is taken from `zendesk/lib/vars.rb` to …
=> Add Validation for Account Subdomain & Email

Gemfile.lock, lib/zendesk_apps_tools/api_connection.rb, lib/zendesk_apps_tools/version.rb, spec/lib/zendesk_apps_tools/api_connection_spec.rb
/cc @zendesk/vegemite :v:
After adding validation for username which is end user's email. I have not considered for users who uses API token. 
The previous regular expression for email was
```
EMAIL_REGEX  = /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i
```
This is now changed to 
```
EMAIL_REGEX  = /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})(\/token:\S+)?$/i
```
* https://zendesk.slack.com/archives/C1230V1CG/p1544631643154400
* [low] Attempt to fix ZAT login with email that requires api_token
=> Fix email validation

Gemfile.lock, lib/zendesk_apps_tools/api_connection.rb, lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/deploy_spec.rb
:v:
In the past, when a wrong `subdomain` or `username` is entered during a `zat_update` or `zat_create`, the connection fails and these details are stored in a cache file locally. In subsequent attempts, zat will look into the local cache file to reconnect using the wrong `subdomain` or `username`. 
This is because `subdomain` and `username` are stored directly after user prompts. Instead, they should be stored after a successful connection. This successful connection occurs and is defined when API `response.body['status']` is [**completed**](https://github.com/zendesk/zendesk_apps_tools/blob/master/lib/zendesk_apps_tools/deploy.rb#L112).
Felt that this is a good place to cache [instance variables `subdomain` and …
=> Relocate cache.save zat_details

README.md
:v:
Fixes link to ZAT in developer docs.
* None - docs only change.
=> Fix link to ZAT in developer docs

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
⚠️ *** DO NOT MERGE EVEN WITH 2 +1s *** ⚠️ 
This change requires devqa first.
There was a need to bump a dependency in zendesk_apps_support to address a security alert.  This change is to bump zendesk_apps_support in zendesk_apps_tools to make sure that the patched version of zas is being used in zat.
* JIRA: https://zendesk.atlassian.net/browse/AF-1509
* https://github.com/zendesk/zendesk_apps_support/pull/220
* https://github.com/zendesk/zendesk_apps_support/compare/f5166cf783b726f0f96a3e6c9972def99312182c...90dbafcf1b8cb9b6fc5f4e14c1143c9b9021e2a8
* Medium: Significant bump of zas in zat.  zas has not been bumped in about a year.  Could cause zat to break in unknown ways due to accumulated changes over said period.
=> [AF-1509] Bump zendesk_apps_support to 4.12.4

lib/zendesk_apps_tools/theme.rb
This parameter is no longer used by the internal API.
The user can now set the `role` via the preview UI.
@zendesk/vegemite Can you guys release a new version, please? :)
cc @zendesk/delta
=> Remove role option from Theming Center tool

lib/zendesk_apps_tools/api_connection.rb
If any of the environment variables `ZAT_{URL,USERNAME,PASSWORD}` are
set they will be used in place of an interactive prompt.
=> Allow setting the url, username and password non-interactively

Gemfile.lock, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb, zendesk_apps_tools.gemspec
@zendesk/wombat 
Take 2 - fixing bad merge with master
- ZAS bump which exposes the plan information to app developers
- allow plan argument to be passed in zat server and to be put in the .zat file
* JIRA: https://zendesk.atlassian.net/browse/APPS-4597
* low - breaks `zat server`
=> Expose plan information to app developers - allow `--plan=gold` and plan in .zat file - take 2

lib/zendesk_apps_tools/command.rb
:v:
/cc @zendesk/vegemite, @zendesk/dingo
As part of the automated security checks, we want **ZAS** validation warnings to appear in **ZAT** and **ZAM** (via `Apps Approval`)
One of the checks involve checking for secrets and api-keys that developers might have accidentally left in the code base - this is **not a blocking error**, however, **we want to warn developers about this**.
**ZAS** will pass these warnings to **ZAT** via an attribute called `warnings` in an instance of class **ZendeskAppsSupport::Package** (Checkout in ZAS)
**instance creation:**
`app_package = ZendeskAppsSupport::Package.new(app_directory.to_s)`
**instance.warnings:**
we execute `app_package.validate` somewhere resulting in `app_package.warnings` being filled if there are any warnings
**displaying warnings**
We …
=> Ensure warnings raised from ZAS are consistent with internal warnings

zendesk_apps_tools.gemspec
:v:
This PR is to bump the required Ruby version for ZAT to 2.1 or above. I do not think this PR will work on its own as ZAT has dependencies on ZAS which currently requires Ruby 2.3 for the i18n gem. Argh!
* JIRA: https://zendesk.atlassian.net/browse/AF-1478
* [HIGH | medium | low] Does it work on windows?
* [HIGH | medium | low] Does it work in the different products (Support, Chat)?
* [HIGH | medium | low] Are there any performance implications?
* [HIGH | medium | low] Any security risks?
* [HIGH | medium | low] What features does this touch?
=> [AF-1478] Bump ruby version to 2.1

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v: /cc @zendesk/vegemite, @zendesk/dingo 
Bumping ZAT to 2.14 for release. Changes should inherit ZAT v4.18 as a direct dependency
Changes would include
- [Update Source Validation and Remove jshintrb](https://github.com/zendesk/zendesk_apps_support/pull/234), and
- [Add strings for insecure and block-listed request warnings/errors](https://github.com/zendesk/zendesk_apps_support/pull/231).
* JIRA: https://zendesk.atlassian.net/browse/MPORT-443
* JIRA: https://zendesk.atlassian.net/browse/MPORT-498
* [low] ZAT command does not print the right warnings
=> Bump ZAT to 3.1 with ZAS v4.18.

Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
/cc @zendesk/vegemite @zendesk/dingo 
Bump Version to 3.1.1 which is actually secretly 3.0.0. This is because ZAT 3.1.0 is a bad version
* [low] ZAT doesnt work. Cannot deploy apps
=> Bump ZAT to v3.1.1

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v:
Quite similar to the previous [ZAS bump](https://github.com/zendesk/zendesk_apps_support/pull/243). I am pushing this up to see if it successfully builds on travis. This is bumped manually to avoid rake bump minor which would bump the bundle with version in Gemfile. 
* [low] All the QA test has been done and approved in previous tasks, in ZAS.
=> Bump ZAT to v3.2.0

README.md
:v:
`bump patch|minor|major` by default runs a bundle update on zat.  It is possible to circumvent this by appending `--no-bundle` to said command.  This change is to document this in the Readme.
* JIRA: https://zendesk.atlassian.net/browse/AF-1656
None. Updating README.md only.
=> [AF-1656] Articulate how to safely bump ZAT

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
/cc @zendesk/vegemite @zendesk/dingo 
Bumping ZAS in ZAT to version 4.22.0
* JIRA: https://zendesk.atlassian.net/browse/MPORT-580
* After merging this PR, Create ZAT tag version 3.3.0, Gem build and release to RubyGems.
* [low] ZAT validate, create and upload fails
=> [MPORT-580] Bump ZAS to version 4.22.0 in ZAT

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v:
/cc @zendesk/vegemite @zendesk/dingo 
Bumping ZAS in ZAT to version 4.23.0
-After merging this PR, Create ZAT tag version 3.4.0, Gem build and release to RubyGems.
* JIRA: https://zendesk.atlassian.net/browse/APPS-4832
* [low] ZAT server fails
=> Bump ZAS to v4.23.0

lib/zendesk_apps_tools/theme.rb, lib/zendesk_apps_tools/theming/common.rb
:v:
Themes define a `api_version` in the manifest but this wasn't being sent to the server.
* JIRA: [GG-889]
* low - only for the themes utility
[GG-889]: https://zendesk.atlassian.net/browse/GG-889
=> Support api version in zat theme preview

Gemfile.lock, lib/zendesk_apps_tools/server.rb
:v:
`zd-staging.com` was changed to `zendesk-staging.com` a long time ago. This old regex means `?zat=true` does not function correctly on staging (more specific the reload doesn't work).
* JIRA: https://zendesk.atlassian.net/browse/AF-XXX
* [none] only affects staging
=> Update REGEX for staging

lib/zendesk_apps_tools/server.rb
:v:
Allow `futuresimple` and `local.futuresimple` in the regex, so they will get CORS headers when using `?zat=true`
* JIRA: https://zendesk.atlassian.net/browse/AF-XXX
* [none] Added new domains to regex
=> Allow futuresimple for CORS

.travis.yml, Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
/cc @zendesk/dingo 
[JIRA story](https://zendesk.atlassian.net/browse/APPS-4945).
In this implementation, I have added a before_install script `gem install bundler -v 1.17.3` because that is the current default bundler version that supports ruby version 2.1 through to 2.4
Also, we need ZAS bumped to support custom objects when it becomes available.
* [low] Bumping ZAS in ZAT.
=> [APPS-4945]Use ZAS v4.27.0 and BUMP ZAT v3.6.1

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Bumping zendesk_apps_support version in order to get new available location `visit_editor` from zendesk_apps_support's latest release
* JIRA: https://zendesk.atlassian.net/browse/SFP-841
* [low] Does it work on windows? Should not be affected
* [low] Does it work in the different products (Support, Chat)? Should not be affected
* [low] Are there any performance implications? No
* [low] Any security risks? No
* [low] What features does this touch? Locations update
=> Bump of zendesk_apps_support dependency

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Failed to build gem dependency(native extensions) thin server on MacOS 10.15.6
Solution is to bump thin version from 1.7.2 to 1.8.0
* https://github.com/macournoyer/thin/issues/370
=> Bump thin from 1.7.2 to 1.8.0

Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
* Bump ZAT to 3.8.2.
* Bump mimemagic to 0.3.10 since 0.3.5 seems to have been pulled from RubyGems.
* JIRA: https://zendesk.atlassian.net/browse/VEG-486
* Medium.  [Minor version gem bump of thin](https://github.com/zendesk/zendesk_apps_tools/pull/354).  Might break anything that requires use of the thin client, like `zat server`.
* Low.  Patch version bump of mimemagic.  I think that this is used for assets, so could break anything involving uploading things, like `zat update`.
=> [VEG-486] Bump ZAT to 3.8.2

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v:
Let's bump zendesk_apps_support to 4.29.9, so that we have access to the latest validations.
Compare diff: https://github.com/zendesk/zendesk_apps_support/compare/v4.29.5...v4.29.9
Changes:
* https://github.com/zendesk/zendesk_apps_support/pull/306, version bump, no risk
* https://github.com/zendesk/zendesk_apps_support/pull/304, Add warning for sensitive data in hidden fields, low risk: validations might break.
* https://github.com/zendesk/zendesk_apps_support/pull/303, Add strings for new warning validation, no risk: translations only
* https://github.com/zendesk/zendesk_apps_support/pull/305, Replace mime_type gem with marcel, low risk: drop in gem replacement
* https://github.com/zendesk/zendesk_apps_support/pull/301, version bump, no risk.
* …
=> [VEG-638] Bump zendesk_apps_support to latest

.github/pull_request_template.md, Gemfile.lock, app_template_iframe/manifest.json.tt, lib/zendesk_apps_tools/version.rb
:v:
* Add support for new flexible parameter for the most default of scaffolds.
* Bump the version
* Alter the github template to VEG instead of AF 🥦 
* VEG-601: https://zendesk.atlassian.net/browse/VEG-601
* Low. Adds a new attribute only. New apps might not pass `zat validate` by default.
=> [VEG-601] Add support for new flexible parameter for the most default of scaffolds

.github/workflows/actions.yml, Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v:
We should bump zendesk_apps_support to the latest version so that ZAT can validate on Webhook app requirements.
Also drops support for Ruby 2.5 which has been EOL for almost one year now: https://endoflife.date/ruby .  Nokogiri 1.13.1 drops support for Ruby 2.5.9.
* JIRA: https://zendesk.atlassian.net/browse/VEG-1069
* Low. Might break validations for app requirements.
=> [VEG-1069] Bump zendesk_apps_support to 4.31.1

lib/zendesk_apps_tools/theme.rb
:v:
Im using zendesk_app_tools via vm which mount volume via sshfs. 
I see that you using [listen gem](https://github.com/guard/listen) to manage theme file changes.
Its readme says  
> some filesystems won't work without polling (VM/Vagrant Shared folders, NFS, Samba, sshfs, etc.)
Thats why I added --force-polling option into `zat theme preview`.
* [HIGH | medium | low] Does it work on windows?
* [HIGH | medium | low] Does it work in the different products (Support, Chat)?
* [HIGH | medium | low] Are there any performance implications?
* [HIGH | medium | low] Any security risks?
* [HIGH | medium | low] What features does this touch?
=> Added force_polling option into theme.rb

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/theme.rb, scripts/invoke.sh
:v:
The previous change [here](https://github.com/zendesk/zendesk_apps_tools/pull/378) was not quite enough to support running in Docker, sinatra was not exposed from within the container to the outside world.
This change:
* Sets a `DEFAULT_SERVER_IP` of `'0.0.0.0'` as the Sinatra bind ip ([ref](https://forums.docker.com/t/service-running-on-port-4567-only-replies-within-the-container/27166)) for both `server` and `theme` subcommands.
* Sets the default network to `bridge` when running the container.
* JIRA: https://zendesk.atlassian.net/browse/VEG-1234
* https://github.com/zendesk/zendesk_apps_tools/pull/378
* Medium.  Might break `zat server` or `zat theme preview` when running on Windows.
=> [VEG-1234] Apply additional changes to support running in docker

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Upgrade ZAS to v4.32.0, which will fail validation for apps having http target requirements.
* JIRA: https://zendesk.atlassian.net/browse/DINGO-1663
* [HIGH | medium | low] Does it work on windows?
* [HIGH | medium | low] Does it work in the different products (Support, Chat)?
* [HIGH | medium | low] Are there any performance implications?
* [HIGH | medium | low] Any security risks?
* [HIGH | medium | low] What features does this touch?
low, fail validation for apps having http target requirements
=> [DINGO-1663] Upgrade ZAS

.github/pull_request_template.md, Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
* Bump the version of zendesk_apps_tools to 3.8.10
* Ensure that the repo is bundled to pick up the latest versions of dependencies
* Clarify risks in GH template so that these are prompts for authors only + do not get exposed within pull request opening comments
* JIRA: https://zendesk.atlassian.net/browse/VEG-XXX
* Low. Might break ZAT validation due to changes to Gemfile.lock.
=> Bump version + bundle install

zendesk_apps_tools.gemspec
:v:
The Apache license version text is incorrect, and there is a warning thrown during build time. This fix adds valid license identifier as per https://spdx.org/licenses/
* JIRA: https://zendesk.atlassian.net/browse/AF-XXX
* [HIGH | medium | low] Does it work on windows? 
* [HIGH | medium | low] Does it work in the different products (Support, Chat)? 
* [HIGH | medium | low] Are there any performance implications?
* [HIGH | medium | low] Any security risks?
* [HIGH | medium | low] What features does this touch?
=> Fix Apache license SPDX identifier

Gemfile.lock, lib/zendesk_apps_tools/version.rb
We should lock json at 2.6.1 since it appears that the patch version
bump to json 2.6.2 broke certain functionality handling errors in ZAT,
by causing a panic + broken flow of execution in certain usecases.
:v:
* PR that bumped JSON: https://github.com/zendesk/zendesk_apps_tools/pull/387
Medium. This includes the dependabot change [here](https://github.com/zendesk/zendesk_apps_tools/pull/385) so handle with care.
* Check out this branch
* Run `./bin/zat version`, `./bin/zat server`, `./bin/zat new`.  Check things work.
=> Downgrade json to 2.6.1

lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
- Bump required Ruby to >= 2.6
- Bump required RubyGems version to 3.0.0
- Bump version to 3.9.0
* JIRA: N/A
Low: We've actually been using nokogiri 1.13.x for a while so ZAT
already requires Ruby >= 2.6.
=> Bump Ruby version and ZAT version

.github/workflows/actions.yml, Gemfile.lock
This was an oopsie in my [1]. It doesn't affect `gem install` so only
bringing the lock file to sync without bumping version.
[1] https://github.com/zendesk/zendesk_apps_tools/commit/470a8d6e010970d7b9646304c3b7e17d10694409
* JIRA: N/A
Low: Fixing only version number in the lock file.
=> Fix version in Gemfile.lock being out-of-sync
