zendesk/zendesk_apps_tools

lib/zendesk_apps_tools/bump.rb
=> Set patch as default bump strategy

app_template/templates/layout.hdbs, features/new.feature
=> Proper html5

lib/zendesk_apps_tools/bump.rb, lib/zendesk_apps_tools/manifest_handler.rb
:koala: 
It delegates to shell command execution. The reasons I think it's OK to do so:
1. this is opt in
2. this is not on server side
cc @zendesk/quokka
=> Add the ability to commit and tag after bump

Gemfile.lock
=> bundle update zendesk_apps_support

doc/tools.md
:koala:
/cc @zendesk/quokka @chucknado 
- Jira link: https://zendesk.atlassian.net/browse/AF-154
=> AF-154 add doc

Gemfile.lock, zendesk_apps_tools.gemspec
=> [ZA-17] Bump ZAS to v1.19.0

lib/zendesk_apps_tools/settings.rb, spec/lib/zendesk_apps_tools/settings_spec.rb
:koala:
forgot to convert symbol to string in settings helper
- Jira link: 
- None
=> Symbol to String bug fixed

lib/zendesk_apps_tools/server.rb
:koala:
Seems like we need this since the last [sinatra bump](https://github.com/zendesk/zendesk_apps_tools/pull/107)
- None
=> Access-Control-Allow-Origin: *

lib/zendesk_apps_tools/server.rb
=> Stricter access control

Gemfile.lock, zendesk_apps_tools.gemspec
=> bump zas to 1.21.1

lib/zendesk_apps_tools/translate.rb, spec/lib/zendesk_apps_tools/translate_spec.rb
:v:
/cc @catkins 
Threaded translation.
Like a 100 times faster
Ok 9 times faster. But still... it feels a lot faster
* JIRA: 
- Too much time on your hands
=> Why wait, life is too short

lib/zendesk_apps_tools/deploy.rb
@zendesk/vegemite @zendesk/wombat
=> pretty colours and exit code

features/new.feature, lib/zendesk_apps_tools/command.rb
:v:
replaced --iframe-only with --v2
* JIRA: https://zendesk.atlassian.net/browse/AF-328
=> [AF-328] replaced --iframe-only with --v2

app_template_iframe/assets/iframe.html
🍞
Update iframe only template to include new APIs
* JIRA: https://zendesk.atlassian.net/browse/AF-323
* None (template changes only)
=> [AF-323] Update iframe only template

app_template_iframe/assets/iframe.html
=> Update iframe.html to beta3

app_template_iframe/manifest.json.tt, features/new.feature
:v:
updated template for iframe only
* JIRA:
=> 2.0 in template

Gemfile.lock, zendesk_apps_tools.gemspec
=> Bump ZAS to 1.29

lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/version.rb, spec/lib/zendesk_apps_tools/command_spec.rb, zendesk_apps_tools.gemspec
:v:
Print the version when doing `zat -v` or `zat --version`
* JIRA:
=> version printing

Gemfile, Gemfile.lock, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb, zendesk_apps_tools.gemspec
Support https://github.com/zendesk/zendesk_apps_support/pull/127
Just changes some syntax
cc @zendesk/wombat @zendesk/vegemite 
- [low] `zat server` or `zat validate` doesn't work
=> support refactors in ZAS

bin/zat, lib/zendesk_apps_tools/deploy.rb
=> better error for app not found, color on windows

.travis.yml, features/step_definitions/app_steps.rb, lib/zendesk_apps_tools/common.rb
=> fix password

lib/zendesk_apps_tools/server.rb
:v:
We didn't add cors to the public folder asset requests. Now we do.
* JIRA:
=> add cors to all public folder assets

doc/tools.md
cc @zendesk/vegemite @chucknado extracted from #128 since it might take a little longer to merge.
=> extract docs for zat create and zat update

doc/tools.md, lib/zendesk_apps_tools/api_connection.rb, lib/zendesk_apps_tools/cache.rb, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/command_helpers.rb, lib/zendesk_apps_tools/deploy.rb, spec/lib/zendesk_apps_tools/cache_spec.rb, spec/lib/zendesk_apps_tools/command_spec.rb
@zendesk/vegemite solves https://support.zendesk.com/hc/en-us/community/posts/211654267-suggestion-provide-a-zatfile-parameter-to-zat
https://zendesk.atlassian.net/browse/AF-362
=> AF-362 zatfile

doc/tools.md
Resolves error pointed out by @joelhellman in https://github.com/zendesk/zendesk_apps_tools/commit/d922c4c7b06b5e2f45335cdf6df9e2ed69b9e79f#commitcomment-19438252
=> fix documentation bug

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
https://github.com/zendesk/zendesk_apps_support/compare/v3.1.1...v3.1.3
=> bump ZAS to 3.1.3 to include experiments in manifest

doc/tools.md
:v:
Updated `zat new` command to include the `--v1` prefix
* JIRA: n/a
None
=> update zat new command for v1 apps

lib/zendesk_apps_tools/command.rb
=> colour output of validation errors

app_template_iframe/manifest.json.tt, features/new.feature
=> update location name in template

Gemfile.lock, lib/zendesk_apps_tools/command.rb, lib/zendesk_apps_tools/server.rb, zendesk_apps_tools.gemspec
:v:
This reverts commit c51079ff7cf84fa0b04ab9b0a113308079d39702.
Make name  a thing again!
https://github.com/zendesk/zendesk_apps_tools/pull/137#issuecomment-260105744
We have to merge https://github.com/zendesk/zendesk_apps_support/pull/141 first before this works.
* JIRA:
=> Revert "name is not a thing"

Gemfile.lock, zendesk_apps_tools.gemspec
zas pulls in sassc (ruby bindings for libsass)
=> bump zas and thor

lib/zendesk_apps_tools/server.rb
=> stop using unfortunately named methods

lib/zendesk_apps_tools/settings.rb, spec/lib/zendesk_apps_tools/settings_spec.rb
=> dont crash when the mtime is nil for some reason

doc/tools.md
**Description**
* Fixes broken links in the ZAT doc
=> Fix doc links

spec/lib/zendesk_apps_tools/translate_spec.rb
:v:
Added a regression test for translate update
* JIRA:
=> create_file regression test

app_template_iframe/assets/iframe.html
:v:
Updating Garden to latest version in the demo.
* [low] This won't affect any existing apps, but will allow users who use this going forward to access the most up to date assets.
=> Bump Garden to use version 1.0.0

lib/zendesk_apps_tools/translate.rb, spec/fixture/i18n_app_to_json/translations/en.yml, spec/fixture/i18n_app_to_json/translations/expected.json
:v:
We don't need to include the obsolete translations.
* JIRA:
=> we don't need no obsolete

lib/zendesk_apps_tools/command.rb, spec/lib/zendesk_apps_tools/command_spec.rb
cc @zendesk/vegemite 
Fix `server` command with custom path.
- https://zendesk.atlassian.net/browse/AF-744
- [Low] `zat server` may not work correctly
=> [AF-744] Fix server command with custom path

app_template/translations/en.json, app_template_iframe/translations/en.json, features/fixtures/quote_character_translation.json, features/new.feature
:v:
Fix V2 and V1 default translation files.
* JIRA: https://zendesk.atlassian.net/browse/AF-746
[low] play button still doesn't work
=> [AF-746] Fix default translation files in ZAT

app_template_iframe/translations/en.json, features/fixtures/quote_character_translation.json
:v:
Name is a thing in en.json now.
* JIRA: https://zendesk.atlassian.net/browse/AF-782
=> [AF-782] Translation name

README.md, doc/tools.md, lib/zendesk_apps_tools/command.rb
:v:
Update docs to remove references to removed feature and show sunsetting message instead.
* [none] Docs update.
=> Remove command for new v1 app from docs and add sunsetting message

Gemfile.lock, app_template_iframe/translations/en.json, zendesk_apps_tools.gemspec
🙅‍♂️ Do not merge yet. Waiting on ZAS PR.
:v:
Add name to en.json.
Once ZAS PR has been merged, bump gem version here too.
* JIRA: https://zendesk.atlassian.net/browse/AF-776
* ZAS PR: https://github.com/zendesk/zendesk_apps_support/pull/168
* [low] Validations fail incorrectly locally but apps can still be uploaded.
=> [AF-776] Add name to translation template

Gemfile.lock, zendesk_apps_tools.gemspec
@zendesk/wombat @zendesk/vegemite
=> Bump ZAS to 4.4.2

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
* JIRA: https://zendesk.atlassian.net/browse/AF-819
=> [AF-819] Bump ZAS

Gemfile.lock, zendesk_apps_tools.gemspec
=> Bump ZAS to v4.6.1

app_template_iframe/assets/iframe.html
:v:
Have the template point to the latest Zendesk Garden styles.
* Relates to: https://zendesk.atlassian.net/browse/AF-887
=> Update version of Zendesk Garden used in template

lib/zendesk_apps_tools/translate.rb, spec/lib/zendesk_apps_tools/translate_spec.rb
We currently fetch the locales from https://support.zendesk.com/api/v2/locales.json. However, other products may have more languages than Support.
Following the approach taken in https://github.com/zendesk/client-i18n-tools, adding a new option `--locales=./path/to/locales.json` to `translate update` command for the user to provide a list of locales.
> User can pass in absolute or relative path of the json file
Existing usage of `zat translate update` should still be working. Current logic is untouched.
@zendesk/vegemite - please help release a new version too as it will help unblock a few things. Many thanks!
=> Add option to provide a list of locales to fetch

lib/zendesk_apps_tools/theming/server.rb
Jira: https://zendesk.atlassian.net/browse/HCD-1559
Fixes local asset loading for file types that require CORS (e.g. fonts):
@zendesk/vegemite @zendesk/delta
=> Add CORS headers to local theming asset server

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Bump ZAS to v4.7.0 
* None
=> Bump ZAS to v4.7.0

lib/zendesk_apps_tools/command.rb
Related to https://github.com/zendesk/zendesk_apps_tools/issues/223
=> Require date on check_for_update

lib/zendesk_apps_tools/command.rb
We can't update CFA currently: https://samson.zende.sk/projects/conditional_fields_app/deploys/454084
skip message when flag set
=> skip message when flag set

lib/zendesk_apps_tools/server.rb
Make apps collapsible in ZAT
- JIRA: https://zendesk.atlassian.net/browse/AF-1062
[low] Apps could become collapsible when they shouldn't
=> [AF-1062] Make apps collapsible in ZAT

doc/tools.md
- Minor updates to links to hc content that's moved
- None
@zendesk/vegemite
=> Update hc links

lib/zendesk_apps_tools/theme.rb
Small change to lookup Theming templates in subfolders too (only 1 level deep).
@zendesk/delta @zendesk/vegemite
=> Add possibility to lookup in subfolders

app_template_iframe/assets/iframe.html
Relates to https://github.com/zendesk/demo_apps/pull/106#issuecomment-407945249
=> Update Garden reference

.github/pull_request_template.md
:v:
Remove the construction emoji and change the wording in Risks. 
* [low] - no risks as this only affects PRs on Github.
=> Correct pull request template per your request

README.md
:v:
- Adds info to the README about contributing to the docs
- N/A - README tweak
- Low: README update
=> Update readme for docs contributions

Gemfile.lock, README.md, zendesk_apps_tools.gemspec
:dog2: :v:
/cc @zendesk/dingo @zendesk/vegemite
Bump ZAS to include validations for:
1. secrets detected inside app text files, and
1. insecure and block-listed requests in app code.
* https://zendesk.atlassian.net/browse/MPORT-443
* https://zendesk.atlassian.net/browse/MPORT-445
* Low - causes alarm/confusion with developers previously unaware of exposed secrets in their code.
* Medium - causes apps with legitimate requests to be rejected.
=> [MPORT-443] [MPORT-445] Bump ZAS to include requests and secrets security validations

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
Reverts zendesk/zendesk_apps_tools#301
Reverting to ZAT version that works
=> Revert "Bump ZAT to 3.1 with ZAS v4.18."

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
Bumping this through a PR to make sure that it builds nicely
* JIRA: https://zendesk.atlassian.net/browse/MPORT-502
* [low] Deployment fails in Samson, ZAT commands doesn't work
=> [MPORT-502 ]  Bump Version to v3.1.2

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
=> [AF-1656] add empty

app_template_iframe/assets/iframe.html
:v:
We should use the minified SDK as outlined here: https://developer.zendesk.com/apps/docs/developer-guide/using_sdk
* [low] Changes from the full SDK to minified.
=> Use minified SDK for `zat new`

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
Bumps ZAS to pull in Sell locations
* JIRA: https://zendesk.atlassian.net/browse/MPORT-548
* Low: breaks Sell apps
=> [MPORT-548] Bump ZAS to pull in Sell locations

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
What it says on the tin
* JIRA: https://zendesk.atlassian.net/browse/DINGO-600
* Low: breaks validation
=> [DINGO-600] Bump ZAS to support custom object requirements

.github/pull_request_template.md
:v:
Update template to add a task for updating changelog.
None.
=> Add task for changelog update in PR template

Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
Bump ZAT to 3.8.1.
* JIRA: https://zendesk.atlassian.net/browse/VEGEMITE-362
* (Low) See risks from previous pr https://github.com/zendesk/zendesk_apps_tools/pull/346
=> [VEGEMITE-362] bump zat to v3.8.1

Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
Bump version to 3.8.7
* JIRA: https://zendesk.atlassian.net/browse/VEG-1234
* Low. Version bump only.
=> Bump version to 3.8.7

lib/zendesk_apps_tools/version.rb
:v:
Several Dependabot PRs have been merged, let's release this as a new tag once we are satisfied all is above board.
* JIRA: https://zendesk.atlassian.net/browse/tbd
* Medium. Several Dependabot PRs merged, might break `zat package` and a few other commands.
=> Bump ZAT to 3.8.8

.github/workflows/actions.yml, .github/workflows/publish.yml, Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
77be3ce7351a5ddc9517aebfc8e14b9ca573d4b2 Publish gem via GH Actions
4b9de0f9b1299c16dba5b3e4ccfecd551bc2b777 Bump version to 3.8.15.beta.2
df230cb10128b6ddf2dcc402032b93a3e2efe968 Fix parsing pre-release gem versions
* JIRA: https://zendesk.atlassian.net/browse/VEG-1430
=> Publish gem via GH Actions

Gemfile.lock, lib/zendesk_apps_tools/version.rb
:v:
QA of the new Github action gem publication workflow.
* JIRA: https://zendesk.atlassian.net/browse/VEG-1430
Low. Beta version bump only, no application code change.
=> [VEG-1430] QA: Bump to 3.8.15.beta.3

Gemfile.lock, zendesk_apps_tools.gemspec
:v:
This PR is to bump ZAS to address a security vulnerability in Nokogiri gem.
* JIRA: https://zendesk.atlassian.net/browse/APPS-6388
Medium: Can break App validations
=> [APPS-6388] Bump ZAS to remove security vulnerability

Gemfile.lock, lib/zendesk_apps_tools/version.rb, zendesk_apps_tools.gemspec
:v:
Fix the rack-livereload version in zendesk_apps_tools.gemspec
* JIRA: https://zendesk.atlassian.net/browse/VEG-XXX
* [low] Fix the rack-livereload version
=> Fix rack-livereload in zendesk_apps_tools.gemspec
